FROM maven:3.5-jdk-8
#COPY ./target/safe-city-1.0.jar /user/data/webapp
#WORKDIR /user/data/webapp
#EXPOSE 8080:8080
#EXPOSE 8000:8000
#CMD ["java", "-jar", "-Dspring.config.location=classpath:default.properties,classpath:production.properties","safe-city-1.0.jar"]