version: "2"
services:
  mongodb:
    container_name: "mongodb"
    image: mongo:3.7
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - /data/db:/data/db
    ports:
        - 27017:27017
    command: mongod --smallfiles --logpath=/dev/null

  api:
    build: ./SafeCityAPI
    working_dir: /SafeCityAPI
    volumes:
      - ./SafeCityAPI:/SafeCityAPI
      - ~/.m2:/home/leon/.m2
    ports: 
      - "8081:8081"
      - "8001:8001"
    command: mvn clean spring-boot:run
    depends_on:
      - mongodb
    restart: always
  
  webapp:
    build: ./SafeCity
    working_dir: /SafeCity
    volumes:
      - ./SafeCity:/SafeCity
      - ~/.m2:/home/leon/.m2
    ports: 
      - "8080:8080"
      - "8000:8000"
    command: mvn clean spring-boot:run
    depends_on:
      - mongodb
      - api
    restart: always