version: "3"
services:
  mongodb:
    container_name: "mongodb"
    image: mongo:4.0
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - /data/db:/data/db
    ports:
        - 27017:27017
    command: mongod --smallfiles --logpath=/dev/null

  api:
    build: ./SafeCityAPI
    working_dir: /SafeCityAPI/target
    volumes:
      - ./SafeCityAPI/target:/SafeCityAPI/target
      - ~/.m2:/home/leon/.m2
    ports: 
      - "8081:8081"
      - "8001:8001"      
    command: java -jar -Dspring.config.location=classpath:default.properties,classpath:production.properties /SafeCityAPI/target/safe-city-api-1.0.jar #mvn clean spring-boot:run -Dspring.config.location=classpath:default.     
    depends_on:
      - mongodb
    restart: always
  
  webapp:
    build: ./SafeCity
    working_dir: /SafeCity/target
    volumes:
      - ./SafeCity/target:/SafeCity/target
      - ~/.m2:/home/leon/.m2
    ports: 
      - "8080:8080"
      - "8000:8000"
    command: java -jar -Dspring.config.location=classpath:default.properties,classpath:production.properties /SafeCity/target/safe-city-1.0.jar
    depends_on:
      - mongodb
      - api
    restart: always

networks:
  network1: