debug=true
server.port=8080
security.basic.enabled=false
spring.thymeleaf.cache=false
logging.level.org.springframework.security=INFO
spring.resources.cache-period=0
spring.thymeleaf.mode=LEGACYHTML5
spring.jackson.serialization.write-dates-as-timestamps:false

api.hostname=localhost
