debug: true
server:
  port: 8081
security:
  basic:
    enabled: true
  user:
    name: SafeCity
    password: SafeCity
spring:
  data:
    mongodb:
      port: 27017
      host: mongodb
      database: brewery


---
spring:
  profiles: dev
  data:
    mongodb:
      port: 27017
      host: localhost
      database: brewery
