server:
  port: 8888
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/LeonFelipeCordero/VU
          search-paths: config-server-properties
  application:
    name: config-server

---
spring:
  profiles: dev
  cloud:
    config:
      server:
        git:
          uri: https://github.com/LeonFelipeCordero/VU
          search-paths: config-server-properties/dev
  application:
    name: config-server
