FROM maven:3.5-jdk-8
#COPY ./target/safe-city-api-1.0.jar /user/data/api
#WORKDIR /user/dataapi
#EXPOSE 8081:8081
#EXPOSE 8001:8001
#CMD ["java", "-jar", "-Dspring.config.location=classpath:default.properties,classpath:production.properties","safe-city-api-1.0.jar"]
